# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 619a056c3460de88b55a910dd3cbfc8ab635de4dabbc8e0681d06e2e17877151f055dd20dd551eeeab45d15d0934cb3061c421d50697ab22a5a595ce09e1694d

test:
  secret_key_base: aad28a59efdf389f00eb580f27fe1188ae9de9dd10a244b8cdaceca3a880fc9dcdf3e84308feb9487bec0e6c6a21e3fa326b813696b99b25a7c0964ff6ea09d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
